### ISSUE TITLE
Error when trying to regen map images

### ISSUE THREAD

**Issue by crazyjoery** [L0laapk3/FactorioMaps#5]
When trying to regenerate the images from a active save that has been generated before it throws a error during the loading stages of the save.

``` __L0laapk3_FactorioMaps__/control.lua:6:
    __L0laapk3_FactorioMaps__/autorun.lua:9:
    '}' expected near ':'
```

Here is the code from the autorun.lua file
```
fm.autorun = {
    name = "No_end/",				-- changing this is currently not supported
    day = true,			 			-- changing this is currently not supported
    night = true,		 			-- changing this is currently not supported
    around_build_range = 5.2,		-- max range from buildings that images will be saved. Feel free to crank this up to very large numbers, it will only render chunks that already exist, it will not generate new ones.
    around_smaller_range = 1,		-- same as above, but smaller range for the following entity types:
    smaller_types = {"lamp", "electric-pole", "radar", "straight-rail", "curved-rail", "rail-signal", "rail-chain-signal", "locomotive", "cargo-wagon", "fluid-wagon", "car"},
    date = "07/10/18",
    mapInfo = {seed =1069981988,maps ={{tick =3395,path ="1",date ="07/10/18",mods ={AGoodStart ="0.1.0","Additional-Turret-016":"0.2.1",AlternativeSteam ="1.0.2","Armored-train":"0.1.11",AtomicArtillery ="0.1.5",AutoDeconstruct ="0.1.11",Automatic_Coupler_016 ="1.0.4",Big_Brother ="0.4.6",Big_Brother_Bobs_plugin ="0.1.7",Bio_Industries ="2.6.12",Blueprint_Flip_Turn ="1.0.0","BurnerLeech A16 Fix":"0.1.8",BurnysTSBC ="0.1.3","Clowns-AngelBob-Nuclear":"1.0.1","Clowns-Extended-Minerals":"1.0.10","Clowns-Locale":"1.0.2","Clowns-Nuclear":"1.2.0","Clowns-Processing":"1.2.8",Crafting_Speed_Research ="0.2.0",Dirt_Path_Redux ="1.2.1",EarlyTrains ="0.16.0",EvoGUI ="0.4.302","Explosive Termites":"1.1.11",FARL ="2.1.2",FNEI ="0.1.9","FactorioExtended-Core":"0.3.1","FactorioExtended-Equipment":"0.3.1","FactorioExtended-Logistics":"0.3.1","FactorioExtended-Machines":"0.3.1","FactorioExtended-Plus-Core":"0.1.4","FactorioExtended-Plus-Equipment":"0.1.2","FactorioExtended-Plus-Logistics":"0.1.4","FactorioExtended-Plus-Machines":"0.1.4","FactorioExtended-Plus-Power":"0.1.3","FactorioExtended-Plus-Storage":"0.1.4","FactorioExtended-Plus-Transport":"0.1.6","FactorioExtended-Plus-Weaponry":"0.1.5","FactorioExtended-Power":"0.3.1","FactorioExtended-Storage":"0.3.1","FactorioExtended-Trains":"0.3.1","FactorioExtended-Transport":"0.3.1","FactorioExtended-Weaponry":"0.3.1","Flare Stack":"2.1.7",ForceFields2 ="2.1.4",FuelTrainStop ="0.16.2",FusionTrain ="0.16.2",GDIW ="0.16.2",Horns ="1.0.2",IncendiaryMunitions ="0.3.1",InlaidLamps ="0.1.0",L0laapk3_FactorioMaps ="1.1.0","LTN-easier":"0.1.0",LoaderRedux ="1.2.7",LogisticTrainNetwork ="1.8.2",Nanobots ="2.0.7",NapalmArtillery ="0.16.4",NauvisDay ="1.0.148",NuclearArtillery ="0.1.1",PCP ="0.0.9",RealisticDecorationCleanup ="0.16.2",RealisticReactors ="2.0.2","RealisticReactors-utilities":"0.16.4","Reinforced-Walls":"0.16.0",SantasNixieTubeDisplay ="0.1.6",ScanningRadar ="0.2.9",Senpais_Trains ="1.2.1",ShinyAngelGFX ="0.16.8",ShinyBobGFX ="0.16.21",SpaceMod ="0.3.12","Squeak Through":"1.2.2",SteamCracking ="1.0.1","TrainSpeedLimit-016":"1.2.0",UnminableVehicles ="1.0.0",UsefulMapColors ="1.1.10",VehicleSnap ="1.16.0",WarehouseAddons ="0.1.1",WaterWell ="1.0.19",Waterfill_v15 ="0.1.3",ZAdv_example ="1.1.5",ZAdv_ruins ="1.0.1",ZAdventure ="2.16.4","aai-programmable-structures":"0.4.4","aai-programmable-vehicles":"0.4.8","aai-signals":"0.3.3","aai-vehicles-chaingunner":"0.3.1","aai-vehicles-flame-tank":"0.2.1","aai-vehicles-flame-tumbler":"0.3.1","aai-vehicles-hauler":"0.3.1","aai-vehicles-laser-tank":"0.3.1","aai-vehicles-miner":"0.3.5","aai-vehicles-warden":"0.2.1","aai-zones":"0.3.4","angels-petrochem-nitrogen-fix":"0.0.3","angelsaddons-oresilos":"0.4.0","angelsaddons-petrotrain":"0.3.3","angelsaddons-pressuretanks":"0.3.0","angelsaddons-smeltingtrain":"0.1.2","angelsaddons-warehouses":"0.3.0",angelsbioprocessing ="0.5.9",angelsindustries ="0.1.0",angelsinfiniteores ="0.7.3",angelspetrochem ="0.7.12",angelspetrochemNaOH ="16.36.1",angelsrefining ="0.9.14",angelssmelting ="0.4.6",base ="0.16.51","battery-recolor":"0.1.2",beautiful_bridge_railway ="0.1.3","bob-basic-belt-reskin":"0.16.1","bobangels-pipe-fix":"0.16.6",bobassembly ="0.16.1",bobelectronics ="0.16.0",bobenemies ="0.16.0",bobgreenhouse ="0.16.0",bobinserters ="0.16.8",boblibrary ="0.16.6",boblogistics ="0.16.23",bobmining ="0.16.0",bobmods_gfxtweak ="0.16.0",bobmodules ="0.16.0",bobores ="0.16.2",bobplates ="0.16.5",bobpower ="0.16.8",bobrevamp ="0.16.3",bobtech ="0.16.6",bobvehicleequipment ="0.16.2",bobwarfare ="0.16.7","bullet-trails":"0.3.1",cheaper_rail_and_concrete ="1.2.0","concrete-and-stone-016":"0.2.5","even-distribution":"0.2.10","expanded-rocket-payloads":"0.16.5",extendedangels ="0.1.5","folk-shuttle":"0.1.13",helmod ="0.7.11",lightorio ="0.16.4","long-reach-research-upgrade":"0.4.3","multi-product-recipe-details":"0.16.4",nicefill ="0.1.5","ore-eraser":"1.4.1",osha_safety ="0.0.2",platforms ="18.5.2",pushbutton ="0.16.0",railloader ="0.5.1","recursive-blueprints":"0.16.2","research-queue":"1.6.7","rso-mod":"3.8.1",scattergun_turret ="3.8.0",textplates ="0.3.3","upgrade-planner":"1.5.3","walls-block-spitters":"0.3.1",xcompat_bobvehicleequipment ="0.16.2"},surfaces ={nauvis ={spawn ={y =0,x =0},zoom ={min =18,max =20},playerPosition ={y =6.84375,x =77.046875},day ="true",night ="true"}}}}},			-- changing this is not supported
    chunkCache = {
		["3395"] = {nauvis ="-3 -1|-3 0|-3 1|-3 2|-3 3|-1 -5|-2 -3|-1 -4|-1 -3|-2 -2|-2 -1|-1 -2|-1 -1|-2 0|-2 1|-1 0|-1 1|-2 2|-2 3|-1 2|-1 3|-2 4|-2 5|-1 4|-1 5|0 -5|1 -6|1 -5|0 -4|0 -3|1 -4|1 -3|0 -2|0 -1|1 -2|1 -1|0 0|0 1|1 0|1 1|0 2|0 3|1 2|1 3|0 4|0 5|1 4|1 5|0 6|1 6|2 -6|2 -5|3 -6|3 -5|2 -4|2 -3|3 -4|3 -3|2 -2|2 -1|3 -2|3 -1|2 0|2 1|3 0|3 1|2 2|2 3|3 2|3 3|2 4|2 5|3 4|3 5|2 6|3 6|4 -6|4 -5|5 -6|5 -5|4 -4|4 -3|5 -4|5 -3|4 -2|4 -1|5 -2|5 -1|4 0|4 1|5 0|5 1|4 2|4 3|5 2|5 3|4 4|4 5|5 4|5 5|4 6|6 -6|6 -5|7 -5|6 -4|6 -3|7 -4|7 -3|6 -2|6 -1|7 -2|7 -1|6 0|6 1|7 0|7 1|6 2|6 3|7 2|7 3|6 4|6 5|7 4|8 -5|8 -4|8 -3|9 -3|8 -2|8 -1|9 -2|9 -1|8 0|8 1|9 0|9 1|8 2|8 3|9 2|8 4"}
	}		-- changing this is not supported
}
```

**Comment by L0laapk3** [comment]
Strange problem, shouldnt take too long to fix

**Comment by L0laapk3** [comment]
should be resolved in v1.2.0.

**Comment by crazyjoery** [comment]
Problem still persists but different error this time around. 

```
__L0laapk3_FactorioMaps__/autorun.lua:9:
    '}' expected near '='
```

**Comment by L0laapk3** [comment]
Sorry about that. Can you try this new version?

**Comment by crazyjoery** [comment]
No worries I'll give it a try tomorrow

**Comment by crazyjoery** [comment]
problem resolved
